In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
a = [1, 2, 3, 4, 5]
df =  pd.Series(a)
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
df.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [5]:
df.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [6]:
a = {"name": "Saikot","age": 25, "city": "Rajshahi"}
df =  pd.Series(a)
print(df)

name      Saikot
age           25
city    Rajshahi
dtype: object

In [7]:

a = {"name":["Saikot","Sakib","Alvi"], "age": [25,26,26], "city": ["Rajshahi","Dhaka","Khulna"]}
df =  pd.Series(a)
print(df)

name        [Saikot, Sakib, Alvi]
age                  [25, 26, 26]
city    [Rajshahi, Dhaka, Khulna]
dtype: object

In [8]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, name to city
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 48.0+ bytes

In [9]:
a = {"n1": ["Saikot","Sakib"],
     "n2": ["Alvi","Saef"],
     "n3": ["Maruf","Mridha"]
     }

df = pd.Series(a,index=["n1","n2","n3"])
df

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [10]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, n1 to n3
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [11]:
df.head()

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [12]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [14]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a,columns= ["Numbers"])
print(df)

   Numbers
0        1
1        2
2        3
3        4
4        5

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Numbers  5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

2 Dimentional Data

In [16]:
a = [["Name","Age","Profession"],["Saikot",26,"Student"]]
df =  pd.DataFrame(a, columns=["Name","Age","Profession"])
print(df)

     Name  Age  Profession
0    Name  Age  Profession
1  Saikot   26     Student

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        2 non-null      str
 1   Age         2 non-null      object
 2   Profession  2 non-null      str
dtypes: object(1), str(2)
memory usage: 180.0+ bytes

In [23]:
a = {"Name": ["Saikot","Sakib","Alvi"],
     "Age": [26,27,28],
     "Profession": ["Student","Job Holder","Student"]
     }

df = pd.DataFrame(a,index=["1","2","3"])
df

     Name  Age  Profession
1  Saikot   26     Student
2   Sakib   27  Job Holder
3    Alvi   28     Student

In [20]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, Name to Profession
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [21]:
df.describe()

count                         3
unique                        3
top       [Saikot, Sakib, Alvi]
freq                          1
dtype: object

In [ ]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [31]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [32]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"})

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [35]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher

In [36]:
df=df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

In [37]:
df

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher