In [2]:
#pip install pandas

In [3]:
import pandas as pd

In [4]:
a = [1, 2, 3, 4, 5]
df =  pd.Series(a)
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
df.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [6]:
df.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [7]:
a = {"name": "Saikot","age": 25, "city": "Rajshahi"}
df =  pd.Series(a)
print(df)

name      Saikot
age           25
city    Rajshahi
dtype: object

In [8]:

a = {"name":["Saikot","Sakib","Alvi"], "age": [25,26,26], "city": ["Rajshahi","Dhaka","Khulna"]}
df =  pd.Series(a)
print(df)

name        [Saikot, Sakib, Alvi]
age                  [25, 26, 26]
city    [Rajshahi, Dhaka, Khulna]
dtype: object

In [9]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, name to city
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 48.0+ bytes

In [10]:
a = {"n1": ["Saikot","Sakib"],
     "n2": ["Alvi","Saef"],
     "n3": ["Maruf","Mridha"]
     }

df = pd.Series(a,index=["n1","n2","n3"])
df

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [11]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, n1 to n3
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [12]:
df.head()

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [13]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [15]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a,columns= ["Numbers"])
print(df)

   Numbers
0        1
1        2
2        3
3        4
4        5

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Numbers  5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

2 Dimentional Data

In [17]:
a = [["Name","Age","Profession"],["Saikot",26,"Student"]]
df =  pd.DataFrame(a, columns=["Name","Age","Profession"])
print(df)

     Name  Age  Profession
0    Name  Age  Profession
1  Saikot   26     Student

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        2 non-null      str
 1   Age         2 non-null      object
 2   Profession  2 non-null      str
dtypes: object(1), str(2)
memory usage: 180.0+ bytes

In [19]:
a = {"Name": ["Saikot","Sakib","Alvi"],
     "Age": [26,27,28],
     "Profession": ["Student","Job Holder","Student"]
     }

df = pd.DataFrame(a,index=["1","2","3"])
df

     Name  Age  Profession
1  Saikot   26     Student
2   Sakib   27  Job Holder
3    Alvi   28     Student

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 96.0+ bytes

In [21]:
df.describe()

        Age
count   3.0
mean   27.0
std     1.0
min    26.0
25%    26.5
50%    27.0
75%    27.5
max    28.0

In [22]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [24]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [25]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"})

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [26]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher

In [27]:
df=df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

In [28]:
df

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      str
 1   col2    3 non-null      int64
 2   Col3    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [30]:
df = df.rename({"col1":"Name","col2":"Age","Col3":"Profession"},axis=1)

In [31]:
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [32]:
data = {
    "City": ["Dhaka","Dhaka","Dhaka",
             "Khulna","Khulna","Khulna"],
    "Day": ["Day1","Day2","Day3",
            "Day1","Day2","Day3"],
    "Temperature": [30,31,29,32,33,31]
}

df = pd.DataFrame(data)

print(df)

     City   Day  Temperature
0   Dhaka  Day1           30
1   Dhaka  Day2           31
2   Dhaka  Day3           29
3  Khulna  Day1           32
4  Khulna  Day2           33
5  Khulna  Day3           31

In [33]:
df.ndim

2

In [34]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,None,28],
     "Profession": ["Student",None,"Teacher"]
    }

df = pd.DataFrame(a)
df

     Name   Age Profession
0  Saikot  26.0    Student
1   Sakib   NaN        NaN
2    Saef  28.0    Teacher

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         2 non-null      float64
 2   Profession  2 non-null      str
dtypes: float64(1), str(2)
memory usage: 204.0 bytes

In [36]:
df.ndim

2

[] means one dimentional data,
[[]] means two dimentional data,
[[[]]] meas three dimentional data

In [37]:
df[["Age"]]

    Age
0  26.0
1   NaN
2  28.0

In [38]:
df.ndim

2

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         2 non-null      float64
 2   Profession  2 non-null      str
dtypes: float64(1), str(2)
memory usage: 204.0 bytes

In [40]:
#df[["Age"]].astype("int32")

In [41]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Salary": [25000,30000,80000],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Salary Profession
0  Saikot   25000    Student
1   Sakib   30000    Student
2    Saef   80000    Teacher

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Salary      3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [43]:
df=df[["Salary"]].astype("int64")

In [44]:
df.Salary

0    25000
1    30000
2    80000
Name: Salary, dtype: int64

In [45]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Salary": [25000,30000,80000],
     "pro": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Salary      pro
0  Saikot   25000  Student
1   Sakib   30000  Student
2    Saef   80000  Teacher

In [46]:
df.Salary

0    25000
1    30000
2    80000
Name: Salary, dtype: int64

In [47]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Salary": [25000,30000,80000],
     "pro": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Salary      pro
0  Saikot   25000  Student
1   Sakib   30000  Student
2    Saef   80000  Teacher

In [48]:
df[["Salary"]]

   Salary
0   25000
1   30000
2   80000

In [49]:
df[df["Salary"]>25000]

    Name  Salary      pro
1  Sakib   30000  Student
2   Saef   80000  Teacher

In [50]:
df[["Salary"]]>25000

   Salary
0   False
1    True
2    True

In [51]:
df[df["Salary"]>25000]["pro"]

1    Student
2    Teacher
Name: pro, dtype: str

In [52]:
df[df["Salary"]>25000]["Name"]

1    Sakib
2     Saef
Name: Name, dtype: str

In [53]:
Data = {
    "Name": ["Saikot","Pranto","Rizvi"],
    "Age" : [25,27,23],
    "Occupation" : ["Job Holder","Job Seeker","Student"]
    }
df = pd.DataFrame(Data)
df

     Name  Age  Occupation
0  Saikot   25  Job Holder
1  Pranto   27  Job Seeker
2   Rizvi   23     Student

In [54]:
Data = {
    "name": ["Shuvo","Sabbir","Asad"],
    "age" : [24,26,28],
    "occupation" : ["Student","Job Holder","Job Holder"]
    }
df1 = pd.DataFrame(Data)
df1

     name  age  occupation
0   Shuvo   24     Student
1  Sabbir   26  Job Holder
2    Asad   28  Job Holder

In [55]:
new_df = pd.concat([df,df1])

In [56]:
new_df

     Name   Age  Occupation    name   age  occupation
0  Saikot  25.0  Job Holder     NaN   NaN         NaN
1  Pranto  27.0  Job Seeker     NaN   NaN         NaN
2   Rizvi  23.0     Student     NaN   NaN         NaN
0     NaN   NaN         NaN   Shuvo  24.0     Student
1     NaN   NaN         NaN  Sabbir  26.0  Job Holder
2     NaN   NaN         NaN    Asad  28.0  Job Holder

In [57]:
new_df = pd.concat([df,df1],axis=1)

In [58]:
new_df

     Name  Age  Occupation    name  age  occupation
0  Saikot   25  Job Holder   Shuvo   24     Student
1  Pranto   27  Job Seeker  Sabbir   26  Job Holder
2   Rizvi   23     Student    Asad   28  Job Holder

In [59]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [25,30,80],
     "Occupation": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Occupation
0  Saikot   25    Student
1   Sakib   30    Student
2    Saef   80    Teacher

In [60]:
Data = {
    "Name": ["Shuvo","Sabbir","Asad"],
    "Age" : [24,26,28],
    "Occupation" : ["Student","Job Holder","Job Holder"]
    }
df1 = pd.DataFrame(Data)
df1

     Name  Age  Occupation
0   Shuvo   24     Student
1  Sabbir   26  Job Holder
2    Asad   28  Job Holder

In [61]:
df2 = pd.concat([df,df1])

In [62]:
df2

     Name  Age  Occupation
0  Saikot   25     Student
1   Sakib   30     Student
2    Saef   80     Teacher
0   Shuvo   24     Student
1  Sabbir   26  Job Holder
2    Asad   28  Job Holder

In [63]:
df2 = pd.concat([df,df1],ignore_index=True)

In [64]:
df2

     Name  Age  Occupation
0  Saikot   25     Student
1   Sakib   30     Student
2    Saef   80     Teacher
3   Shuvo   24     Student
4  Sabbir   26  Job Holder
5    Asad   28  Job Holder

In [65]:
import numpy as np

In [66]:
data = np.random.rand(8,4)

In [67]:
data

array([[0.60596492, 0.50376116, 0.87089276, 0.53608083],
       [0.88340413, 0.67610423, 0.87619464, 0.51672873],
       [0.82233926, 0.89493923, 0.85335152, 0.31429615],
       [0.20212221, 0.37970252, 0.81661551, 0.16003263],
       [0.42282562, 0.63137326, 0.62511658, 0.44239458],
       [0.02575932, 0.16432949, 0.97268689, 0.15482125],
       [0.41500001, 0.153015  , 0.92522824, 0.5977101 ],
       [0.61732284, 0.13202564, 0.5595732 , 0.75198341]])

In [68]:
for c in range(data.shape[1]):
    print(c)

0
1
2
3