In [9]:
#pip install pandas

In [10]:
import pandas as pd

In [11]:
a = [1, 2, 3, 4, 5]
df =  pd.Series(a)
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
df.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [13]:
df.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [14]:
a = {"name": "Saikot","age": 25, "city": "Rajshahi"}
df =  pd.Series(a)
print(df)

name      Saikot
age           25
city    Rajshahi
dtype: object

In [15]:

a = {"name":["Saikot","Sakib","Alvi"], "age": [25,26,26], "city": ["Rajshahi","Dhaka","Khulna"]}
df =  pd.Series(a)
print(df)

name        [Saikot, Sakib, Alvi]
age                  [25, 26, 26]
city    [Rajshahi, Dhaka, Khulna]
dtype: object

In [16]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, name to city
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 48.0+ bytes

In [17]:
a = {"n1": ["Saikot","Sakib"],
     "n2": ["Alvi","Saef"],
     "n3": ["Maruf","Mridha"]
     }

df = pd.Series(a,index=["n1","n2","n3"])
df

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [18]:
df.info()

<class 'pandas.Series'>
Index: 3 entries, n1 to n3
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [19]:
df.head()

n1    [Saikot, Sakib]
n2       [Alvi, Saef]
n3    [Maruf, Mridha]
dtype: object

In [20]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [22]:
a = [1, 2, 3, 4, 5]
df =  pd.DataFrame(a,columns= ["Numbers"])
print(df)

   Numbers
0        1
1        2
2        3
3        4
4        5

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Numbers  5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

2 Dimentional Data

In [24]:
a = [["Name","Age","Profession"],["Saikot",26,"Student"]]
df =  pd.DataFrame(a, columns=["Name","Age","Profession"])
print(df)

     Name  Age  Profession
0    Name  Age  Profession
1  Saikot   26     Student

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        2 non-null      str
 1   Age         2 non-null      object
 2   Profession  2 non-null      str
dtypes: object(1), str(2)
memory usage: 180.0+ bytes

In [26]:
a = {"Name": ["Saikot","Sakib","Alvi"],
     "Age": [26,27,28],
     "Profession": ["Student","Job Holder","Student"]
     }

df = pd.DataFrame(a,index=["1","2","3"])
df

     Name  Age  Profession
1  Saikot   26     Student
2   Sakib   27  Job Holder
3    Alvi   28     Student

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 96.0+ bytes

In [28]:
df.describe()

        Age
count   3.0
mean   27.0
std     1.0
min    26.0
25%    26.5
50%    27.0
75%    27.5
max    28.0

In [29]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [31]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [32]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"})

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [33]:
df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher

In [34]:
df=df.rename({"Name":"col1","Age":"col2","Profession":"Col3"},axis=1)

In [35]:
df

     col1  col2     Col3
0  Saikot    26  Student
1   Sakib    27  Student
2    Saef    28  Teacher

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      str
 1   col2    3 non-null      int64
 2   Col3    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [37]:
df = df.rename({"col1":"Name","col2":"Age","Col3":"Profession"},axis=1)

In [38]:
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [39]:
data = {
    "City": ["Dhaka","Dhaka","Dhaka",
             "Khulna","Khulna","Khulna"],
    "Day": ["Day1","Day2","Day3",
            "Day1","Day2","Day3"],
    "Temperature": [30,31,29,32,33,31]
}

df = pd.DataFrame(data)

print(df)

     City   Day  Temperature
0   Dhaka  Day1           30
1   Dhaka  Day2           31
2   Dhaka  Day3           29
3  Khulna  Day1           32
4  Khulna  Day2           33
5  Khulna  Day3           31

In [40]:
df.ndim

2

In [41]:
a = {"Name": ["Saikot","Sakib","Saef"],
     "Age": [26,27,28],
     "Profession": ["Student","Student","Teacher"]
    }

df = pd.DataFrame(a)
df

     Name  Age Profession
0  Saikot   26    Student
1   Sakib   27    Student
2    Saef   28    Teacher

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      str
 1   Age         3 non-null      int64
 2   Profession  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

[] means one dimentional data,
[[]] means two dimentional data,
[[[]]] meas three dimentional data

In [43]:
df[["Age"]]

   Age
0   26
1   27
2   28

In [44]:
df.ndim

2

In [45]:
df.dtypes

Name            str
Age           int64
Profession      str
dtype: object

In [46]:
df["Age"]

0    26
1    27
2    28
Name: Age, dtype: int64

In [49]:
df[["Age"]].astype("int32")

   Age
0   26
1   27
2   28

In [51]:
df[["Age"]].astype("int8")

   Age
0   26
1   27
2   28

In [52]:
df.Age

0    26
1    27
2    28
Name: Age, dtype: int64

In [59]:
df["Age"]>26

0    False
1     True
2     True
Name: Age, dtype: bool

In [60]:
df[df["Age"]>26]

    Name  Age Profession
1  Sakib   27    Student
2   Saef   28    Teacher

In [61]:
df[df["Age"]>26]["Profession"]

1    Student
2    Teacher
Name: Profession, dtype: str